require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe PatientDiagnosesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # PatientDiagnosis. As you add validations to PatientDiagnosis, be sure to
  # adjust the attributes here as well.
  let!(:patient) { Patient.create( first_name: 'foo', last_name: 'bar', email: 'foo@example.net') }
  let!(:provider) { Provider.create(first_name: 'Biz', last_name: 'Baz', office_address: '999 18th St', office_city: 'Denver', office_state: 'CO') }
  let!(:diagnosis) { Diagnosis.create(diagnosis: 'healthy', diagnosis_code: 'thumbsup') }
  let(:diagnosis_attributes) {
    {
      patient_id: patient.id,
      provider_id: provider.id,
      diagnosis_id: diagnosis.id,
      start_date: "2019-04-01T00:00:00Z",
      end_date: "2019-04-30T00:00:00Z",
    }
  }

  let(:valid_attributes) {
    {
      patient_id: patient.id,
      diagnosis: diagnosis_attributes.reject { |k,v| k == :patient_id }
    }
  }

  let(:invalid_attributes) {
    {
      patient_id: patient.id,
      diagnosis: diagnosis_attributes.merge(provider_id: nil).reject { |k,v| k == :patient_id }
    }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PatientDiagnosesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "returns a success response" do
      patient_diagnosis = PatientDiagnosis.create! diagnosis_attributes
      get :index, params: {patient_id: patient.id}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      patient_diagnosis = PatientDiagnosis.create! diagnosis_attributes
      get :show, params: {id: patient_diagnosis.to_param, patient_id: patient.id}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new PatientDiagnosis" do
        expect {
          post :create, params: valid_attributes, session: valid_session
        }.to change(PatientDiagnosis, :count).by(1)
      end

      it "renders a JSON response with the new patient_diagnosis" do

        post :create, params: valid_attributes, session: valid_session
        expect(response).to have_http_status(:created)
        expect(response.content_type).to eq('application/json')
        expect(response.location).to eq(patient_diagnosis_url(PatientDiagnosis.last))
      end
    end

    context "with invalid params" do
      it "renders a JSON response with errors for the new patient_diagnosis" do

        post :create, params: invalid_attributes, session: valid_session
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq('application/json')
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let!(:diagnosis2) { Diagnosis.create(diagnosis: 'very healthy', diagnosis_code: 'thumbsup') }
      let(:new_attributes) {
        { diagnosis_id: diagnosis2.id }
      }

      it "updates the requested patient_diagnosis" do
        patient_diagnosis = PatientDiagnosis.create! diagnosis_attributes
        expect(patient_diagnosis.diagnosis_id).to eq(diagnosis.id)
        put :update, params: {id: patient_diagnosis.to_param, patient_id: patient.id, diagnosis: new_attributes}, session: valid_session
        patient_diagnosis.reload
        expect(patient_diagnosis.diagnosis_id).to eq(diagnosis2.id)
      end

      it "renders a JSON response with the patient_diagnosis" do
        patient_diagnosis = PatientDiagnosis.create! diagnosis_attributes

        put :update, params: {id: patient_diagnosis.to_param, patient_id: patient.id, diagnosis: valid_attributes[:diagnosis]}, session: valid_session
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to eq('application/json')
      end
    end

    context "with invalid params" do
      it "renders a JSON response with errors for the patient_diagnosis" do
        patient_diagnosis = PatientDiagnosis.create! diagnosis_attributes

        put :update, params: {id: patient_diagnosis.to_param, patient_id: patient.id, diagnosis: invalid_attributes[:diagnosis]}, session: valid_session
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq('application/json')
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested patient_diagnosis" do
      patient_diagnosis = PatientDiagnosis.create! diagnosis_attributes
      expect {
        delete :destroy, params: {id: patient_diagnosis.to_param, patient_id: patient.id}, session: valid_session
      }.to change(PatientDiagnosis, :count).by(-1)
    end
  end

end
