require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe VisitsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Visit. As you add validations to Visit, be sure to
  # adjust the attributes here as well.
  let!(:patient) { Patient.create( first_name: 'foo', last_name: 'bar', email: 'foo@example.net') }
  let!(:provider) { Provider.create(first_name: 'Biz', last_name: 'Baz', office_address: '999 18th St', office_city: 'Denver', office_state: 'CO') }
  let(:visit_attributes) {
    {
      patient_id: patient.id,
      provider_id: provider.id,
      visit_date: "2019-04-01T00:00:00Z",
      notes: "patient spry"
    }
  }

  let(:valid_attributes) {
    {
      patient_id: patient.id,
      visit: visit_attributes.reject { |k,v| k == :patient_id }
    }
  }

  let(:invalid_attributes) {
    {
      patient_id: patient.id,
      visit: visit_attributes.merge(provider_id: nil).reject { |k,v| k == :patient_id }
    }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # VisitsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "returns a success response" do
      visit = Visit.create! visit_attributes
      get :index, params: { patient_id: patient.id }, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      visit = Visit.create! visit_attributes
      get :show, params: {id: visit.to_param, patient_id: patient.id}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Visit" do
        expect {
          post :create, params: valid_attributes, session: valid_session
        }.to change(Visit, :count).by(1)
      end

      it "renders a JSON response with the new visit" do

        post :create, params: valid_attributes, session: valid_session
        expect(response).to have_http_status(:created)
        expect(response.content_type).to eq('application/json')
        expect(response.location).to eq(visit_url(Visit.last))
      end
    end

    context "with invalid params" do
      it "renders a JSON response with errors for the new visit" do

        post :create, params: invalid_attributes, session: valid_session
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq('application/json')
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let!(:provider2) { Provider.create(first_name: 'Foo', last_name: 'Bar', office_address: '999 19th St', office_city: 'Denver', office_state: 'CO') }
      let(:new_attributes) {
        { provider_id: provider2.id }
      }

      it "updates the requested visit" do
        visit = Visit.create! visit_attributes
        expect(visit.provider_id).to eq(provider.id)
        put :update, params: {id: visit.to_param, patient_id: patient.id, visit: new_attributes}, session: valid_session
        visit.reload
        expect(visit.provider_id).to eq(provider2.id)
      end

      it "renders a JSON response with the visit" do
        visit = Visit.create! visit_attributes

        put :update, params: {id: visit.to_param, patient_id: patient.id, visit: valid_attributes[:visit]}, session: valid_session
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to eq('application/json')
      end
    end

    context "with invalid params" do
      it "renders a JSON response with errors for the visit" do
        visit = Visit.create! visit_attributes

        put :update, params: {id: visit.to_param, patient_id: patient.id, visit: invalid_attributes[:visit]}, session: valid_session
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq('application/json')
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested visit" do
      visit = Visit.create! visit_attributes
      expect {
        delete :destroy, params: {id: visit.to_param, patient_id: patient.id}, session: valid_session
      }.to change(Visit, :count).by(-1)
    end
  end

end
